Use mktemp in fmbt-view temporary file creation and clean up the temp file before exit

diff --git a/utils/fmbt-view b/utils/fmbt-view
--- a/utils/fmbt-view
+++ b/utils/fmbt-view
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # fMBT, free Model Based Testing tool
-# Copyright (c) 2011, Intel Corporation.
+# Copyright (c) 2011,2012 Intel Corporation.
 #
 # This program is free software; you can redistribute it and/or modify it
 # under the terms and conditions of the GNU Lesser General Public License,
@@ -50,7 +50,7 @@ shift $(expr $OPTIND - 1)
 
 UTILPATH="$(dirname "$0")"
 if [ "$OUTPUTFILE" == "" ]; then
-	OUTPUTFILE="/tmp/$(basename "$1").$FORMAT"
+        OUTPUTFILE=$(mktemp --suffix ."$FORMAT") || { echo "Can't create temporary file:""$OUTPUTFILE"; exit 1;}
 fi
 
 ( eval $UTILPATH/lsts2dot --loops-in-states -i "$1" $COLORING $LOGFILE | dot -T$FORMAT -o"$OUTPUTFILE" ) && {
@@ -60,5 +60,6 @@ fi
         echo "Displaying..."
         display "$OUTPUTFILE"
     fi
-
 }
+
+rm "$OUTPUTFILE"
